#!/usr/bin/env bash
# Arm an unattended overnight run + watchdog for ANY project, portably.
#
# Usage (run from the project root):
#   overnight-arm.sh <todo.md> [--mode bypassPermissions|acceptEdits]
#                    [--at "<systemd calendar>"] [--watchdog "<cadence>"]
#                    [--no-watchdog] [--disarm]
#
# Defaults: --mode bypassPermissions (an unattended run stalls at its first
# Bash prompt under acceptEdits, and every watchdog relaunch stalls the same
# way), --at = 2 minutes from now, --watchdog = "*:0/30" (every 30 min; the
# launch script's flock + usage-limit snooze make ticks free no-ops while a
# run is alive or a limit is active).
#
# Portability: installs a version-independent shim at ~/.local/bin/
# overnight-launch that resolves the NEWEST installed plugin version at every
# invocation, so armed timers survive plugin updates. Unit names derive from
# the project directory basename, the project path from $PWD.
set -euo pipefail

TODO_FILE="${1:?usage: overnight-arm.sh <todo.md> [--mode M] [--at T] [--watchdog C] [--no-watchdog] [--disarm]}"
shift

MODE="bypassPermissions"
AT=""
WATCHDOG_CAL="*:0/30"
ARM_WATCHDOG=1
DISARM=0
while [ $# -gt 0 ]; do
  case "$1" in
    --mode)        MODE="${2:?--mode needs a value}"; shift 2 ;;
    --at)          AT="${2:?--at needs a systemd calendar value}"; shift 2 ;;
    --watchdog)    WATCHDOG_CAL="${2:?--watchdog needs a cadence}"; shift 2 ;;
    --no-watchdog) ARM_WATCHDOG=0; shift ;;
    --disarm)      DISARM=1; shift ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

PROJECT_DIR="$PWD"
PROJECT_NAME="$(basename "$PROJECT_DIR")"
UNIT="overnight-${PROJECT_NAME}"

if [ "$DISARM" = "1" ]; then
  systemctl --user stop "${UNIT}.timer" "${UNIT}.service" \
    "${UNIT}-watchdog.timer" "${UNIT}-watchdog.service" 2>/dev/null || true
  echo "disarmed ${UNIT} timers (main + watchdog)"
  exit 0
fi

[ -f "$PROJECT_DIR/$TODO_FILE" ] || { echo "FATAL: $TODO_FILE not found under $PROJECT_DIR" >&2; exit 1; }

# Version-independent shim: resolves the newest installed plugin version at
# run time. Re-written on every arm so it tracks shim format changes too.
SHIM="$HOME/.local/bin/overnight-launch"
mkdir -p "$HOME/.local/bin"
cat > "$SHIM" <<'SHIM_EOF'
#!/usr/bin/env bash
# Auto-generated by overnight-arm.sh: forwards to the newest installed
# overnight-runner plugin version so systemd units survive plugin updates.
set -euo pipefail
LATEST="$(ls -d "$HOME"/.claude/plugins/cache/rizonetech/overnight-runner/*/ 2>/dev/null | sort -V | tail -1)"
[ -n "$LATEST" ] || { echo "FATAL: overnight-runner plugin not installed" >&2; exit 127; }
exec bash "${LATEST}scripts/overnight-launch.sh" "$@"
SHIM_EOF
chmod +x "$SHIM"

# Replace any prior units for this project (idempotent re-arm).
systemctl --user stop "${UNIT}.timer" "${UNIT}.service" \
  "${UNIT}-watchdog.timer" "${UNIT}-watchdog.service" 2>/dev/null || true
systemctl --user reset-failed 2>/dev/null || true

[ -n "$AT" ] || AT="$(date -d '+2 minutes' '+%Y-%m-%d %H:%M:00')"

systemd-run --user --on-calendar="$AT" --unit="$UNIT" \
  "$SHIM" "$PROJECT_DIR" "$TODO_FILE" "$MODE"
echo "armed ${UNIT}: starts at ${AT} (mode: ${MODE})"

if [ "$ARM_WATCHDOG" = "1" ]; then
  systemd-run --user --on-calendar="$WATCHDOG_CAL" --unit="${UNIT}-watchdog" \
    "$SHIM" "$PROJECT_DIR" "$TODO_FILE" "$MODE"
  echo "armed ${UNIT}-watchdog: cadence ${WATCHDOG_CAL} (same mode -- a watchdog in a weaker mode stalls on relaunch)"
fi

echo "report logs: $PROJECT_DIR/.claude/overnight/reports/  |  disarm: overnight-arm.sh $TODO_FILE --disarm"
systemctl --user list-timers 2>/dev/null | grep -F "$UNIT" || true
